-- MySQL Script generated by MySQL Workbench
-- Sun Jul 10 22:11:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Rhythm_Records
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customers` ;

CREATE TABLE IF NOT EXISTS `customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` BIGINT(12) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;

ALTER TABLE `customers` AUTO_INCREMENT=1001;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATE NOT NULL,
  `order_total` DECIMAL(10,2) NOT NULL,
  `customers_customer_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `customers_customer_id`),
  INDEX `fk_orders_customers_idx` (`customers_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customers_customer_id`)
    REFERENCES `customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `orders` AUTO_INCREMENT=501;

-- -----------------------------------------------------
-- Table `albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `albums` ;

CREATE TABLE IF NOT EXISTS `albums` (
  `album_id` INT NOT NULL AUTO_INCREMENT,
  `album_name` VARCHAR(45) NOT NULL,
  `release_date` DATE NULL,
  `stock_qty` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`album_id`))
ENGINE = InnoDB;

ALTER TABLE `albums` AUTO_INCREMENT=5001;


-- -----------------------------------------------------
-- Table `orders_has_albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders_has_albums` ;

CREATE TABLE IF NOT EXISTS `orders_has_albums` (
  `orders_albums_id` INT NOT NULL AUTO_INCREMENT,
  `orders_order_id` INT NOT NULL,
  `albums_album_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `line_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`orders_albums_id`, `orders_order_id`, `albums_album_id`),
  INDEX `fk_orders_has_albums_albums1_idx` (`albums_album_id` ASC) VISIBLE,
  INDEX `fk_orders_has_albums_orders1_idx` (`orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_albums_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_albums_albums1`
    FOREIGN KEY (`albums_album_id`)
    REFERENCES `albums` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artists` ;

CREATE TABLE IF NOT EXISTS `artists` (
  `artist_id` INT NOT NULL AUTO_INCREMENT,
  `artist_name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`artist_id`))
ENGINE = InnoDB;

ALTER TABLE `artists` AUTO_INCREMENT=990;


-- -----------------------------------------------------
-- Table `genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genres` ;

CREATE TABLE IF NOT EXISTS `genres` (
  `genres_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genres_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genres_has_albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genres_has_albums` ;

CREATE TABLE IF NOT EXISTS `genres_has_albums` (
  `genres_albums_id` INT NOT NULL AUTO_INCREMENT,
  `genres_genres_id` INT NOT NULL,
  `albums_album_id` INT NOT NULL,
  PRIMARY KEY (`genres_albums_id`, `genres_genres_id`, `albums_album_id`),
  INDEX `fk_genres_has_albums_albums1_idx` (`albums_album_id` ASC) VISIBLE,
  INDEX `fk_genres_has_albums_genres1_idx` (`genres_genres_id` ASC) VISIBLE,
  CONSTRAINT `fk_genres_has_albums_genres1`
    FOREIGN KEY (`genres_genres_id`)
    REFERENCES `genres` (`genres_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genres_has_albums_albums1`
    FOREIGN KEY (`albums_album_id`)
    REFERENCES `albums` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artists_has_albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artists_has_albums` ;

CREATE TABLE IF NOT EXISTS `artists_has_albums` (
  `artists_albums_id` INT NOT NULL AUTO_INCREMENT,
  `artists_artist_id` INT NOT NULL,
  `albums_album_id` INT NOT NULL,
  PRIMARY KEY (`artists_albums_id`, `artists_artist_id`, `albums_album_id`),
  INDEX `fk_artists_has_albums_albums1_idx` (`albums_album_id` ASC) VISIBLE,
  INDEX `fk_artists_has_albums_artists1_idx` (`artists_artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_artists_has_albums_artists1`
    FOREIGN KEY (`artists_artist_id`)
    REFERENCES `artists` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artists_has_albums_albums1`
    FOREIGN KEY (`albums_album_id`)
    REFERENCES `albums` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Insert data to Table `customers`
-- -----------------------------------------------------

INSERT INTO `customers` (`first_name`, `last_name`, `email`, `phone`, `address`)
VALUES
('Robert', 'Smith', 'rmisth@gmail.com', 9984648001, '123 Fake Street, Towner, CO 73892'),
('Amanda', 'Bergen', 'abergen@yahoo.com', 1546140854, '456 Unreal Drive, Cityberg, UT 98903'),
('Jon', 'Johnson', 'jjohnson@hotmail.com', 6135549641, '789 Wheresit Road, Whoville, NY 30432'),
('Jacob', 'Lichtenstein', 'jlicthenstein@aol.com', 8813411452, '987 Theresit Street, Realville, CA 45034'),
('Mark', 'Nunda', 'mnunda@comcast.net', 7763015124, '654 Someplace Avenue, Someplace, WA 53403');


-- -----------------------------------------------------
-- Insert data to Table `artists`
-- -----------------------------------------------------

INSERT INTO `artists` (`artist_name`, `country`)
VALUES
('Nas', 'United States of America'),
('Neutral Milk Hotel', 'United States of America'),
('Summoning', 'Austria'),
('Iggy & The Stooges', 'United States of America'),
('Ed Harris', 'Australia');


-- -----------------------------------------------------
-- Insert data to Table `genres`
-- -----------------------------------------------------

INSERT INTO `genres` (`genre_name`)
VALUES
('East Coast Hiphop'),
('Hardcore Hiphop'),
('Indie Rock'),
('Psychedelic Folk'),
('Black Metal'),
('Ambient/Atmospheric'),
('Proto-Punk'),
('Hard Rock'),
('Soundtrack'),
('Drum and Bass');


-- -----------------------------------------------------
-- Insert data to Table `orders`
-- -----------------------------------------------------

INSERT INTO `orders` (`order_date`, `order_total`, `customers_customer_id`)
VALUES
('2022-04-21', '75.00', 1004),
('2022-04-21', '37.50', 1003),
('2022-05-01', '24.50', 1001),
('2022-05-01', '49.00', 1004),
('2022-05-05', '37.50', 1005);


-- -----------------------------------------------------
-- Insert data to Table `albums`
-- -----------------------------------------------------
INSERT INTO `albums` (`album_name`, `release_date`, `stock_qty`, `price`)
VALUES
('Illmatic', '1994-04-19', 15, '24.50'),
('In the Aeroplane Over the Sea', '1998-02-10', 15, '24.50'),
('Let Mortal Heroes Sing Your Flame', '2001-10-31', 5, '37.50'),
('Raw Power', '1970-02-07', 10, '24.50'),
('Neotokyo GSDF', '2009-03-05', 5, '37.50'),
('It Was Written', '1996-07-02', 5, '24.50');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
